# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Tools
    url: '#skills'
    weight: 1
  - name: Experience
    url: '#experience_research'
    weight: 10
    identifier: 'experience'
  - name: Research Experience
    url: '#experience_research'
    weight: 11
    parent: 'experience'
  - name: Teaching Experience
    url: '#experience_teaching'
    weight: 12
    parent: 'experience'
  - name: Projects
    url: '#featured_projects'
    weight: 20
  - name: Publications
    url: '#publications'
    weight: 30
  - name: Talks
    url: '#talks'
    weight: 40
  - name: Accomplishments
    url: '#accomplishments'
    weight: 50
    identifier: 'accomplishments'
  - name: Achievements & Honors
    url: '#accomplishments'
    weight: 51
    parent: 'accomplishments'
  - name: Summer Schools, Courses, Certifications
    url: 'certificates/'
    weight: 52
    parent: 'accomplishments'
  - name: Posts
    url: '#posts'
    weight: 60
  - name: GalleryðŸ“¸
    url: 'photography/'
    weight: 70

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
